"""Chart output adapter — Phase 4.11.

Emits a tuple of (python_script, json_data). The script is never executed
by kb; the user runs it locally to render a matplotlib bar chart from the
JSON sidecar. All user-controlled strings are JSON-encoded into the
sidecar — never f-string-interpolated into the Python source.
"""

from __future__ import annotations

import json

from kb.query.formats.common import build_provenance, validate_payload_size

_SCRIPT_TEMPLATE = '''"""KB query output — matplotlib visualization script.

Generated by kb.query.formats.chart (Phase 4.11).

Run:
    python <this-script>

Requires: `pip install matplotlib` (not a kb runtime dependency).
"""

import json
from pathlib import Path

import matplotlib.pyplot as plt  # user dependency — run `pip install matplotlib`

HERE = Path(__file__).parent
# JSON sidecar lives next to this script at the same stem with .json extension
DATA_PATH = HERE / (Path(__file__).stem + ".json")
DATA = json.loads(DATA_PATH.read_text(encoding="utf-8"))

PAGES = DATA.get("source_pages", [])
if not PAGES:
    print("No source pages for this query — nothing to chart.")
    raise SystemExit(0)

LABELS = [p["id"] for p in PAGES]
RANKS = [p["rank"] for p in PAGES]
MAX_RANK = max(RANKS)
# Invert ranks so rank 1 (most relevant) becomes the tallest bar
VALUES = [MAX_RANK - r + 1 for r in RANKS]

fig, ax = plt.subplots(figsize=(8, max(3, 0.4 * len(PAGES))))
ax.barh(LABELS[::-1], VALUES[::-1])
ax.set_xlabel("Relevance (inverted rank — higher = more relevant)")
title = DATA.get("question", "")[:80]
ax.set_title(title)
fig.tight_layout()
out_path = HERE / (Path(__file__).stem + ".png")
fig.savefig(str(out_path), dpi=150)
print(f"Wrote {out_path.name}")
'''


def render_chart(result: dict) -> tuple[str, str]:
    """Render a query result as (python_script, json_data) for matplotlib.

    Returns:
        Tuple of (script_str, json_data_str).
        Caller writes script_str to <stem>.py and json_data_str to <stem>.json.
    """
    validate_payload_size(result)

    prov = build_provenance(result)
    pages_data = [
        {"id": pid, "rank": rank}
        for rank, pid in enumerate(result.get("source_pages", []), start=1)
    ]
    data = {
        "question": prov["query"],
        "generated_at": prov["generated_at"],
        "kb_version": prov["kb_version"],
        "source_pages": pages_data,
    }
    json_data = json.dumps(data, indent=2, ensure_ascii=False)
    # Script is template-only; no user data interpolated into code.
    return _SCRIPT_TEMPLATE, json_data
